### PR TITLE
[triqs] update for triqs 2.0

### PR DESCRIPTION
**Pull request by HugoStrand**
Dear Igor,

Here are some fixes for triqs 2.0 support. If you do not want to merge to master could we have a 2.0 side branch?

Cheers, Hugo

### CODE REVIEW

**Comment by krivenko** [comment]
Thank you very much, Hugo!

I will have a look at your changes later this week and merge them into `master`. But before I do this, I'd like to ask a few questions.

* Does your PR make `pomerol2triqs` compatible with TRIQS library tag 2.0?
* Is there a tagged version of the library the current `master` of `pomerol2triqs` is compatible with? The 1.5 library branch has somehow stopped being a thing, while 1.4.2 lacks necessary features, if I remember correctly. I consider preserving the current state of `pomerol2triqs` on a backup branch in case such a tagged version exists.
* Do you by any chance know if we are going to see the 2.1 library release anytime soon?

Best regards,
Igor

**Comment by HugoStrand** [comment]
Dear Igor,

I am not 100% sure that this works on triqs-2.0. I would suggest to put this on a separate branch if you want. We are working on a 2.1 release of triqs and are currently on 2.1-rc1. The working plan is to have this out before the Triqs meeting this summer.

Cheers, Hugo

**Comment by aeantipov** [comment]
Hugo, mind testing it what one of the tagged versions of triqs? 
https://github.com/TRIQS/triqs/releases
This way it would be easy to ensure this always has a chance at working.

**Review by krivenko — APPROVED** [review]

**Comment by krivenko** [comment]
@HugoStrand I made a few attempts at compiling commit f1c89aa42cbe67e54038fa44dede35cee0e692b2 (`master` before this PR was merged), but could not find a compatible combination of cpp2py and triqs. I very much hope that triqs 2.1 (and cpp2py 2.1!) is a well defined release, which would finally allow me to introduce a compatibility guarantee in pomerol2triqs.

**Comment by HugoStrand** [comment]
Dear @krivenko, I am sorry for the state of things. For `triqs-2.1` the dependencies will be slightly simpler to track since `cpp2py` is no longer separate. Best, Hugo

**Pull request merged**
