### PR TITLE
AllFermionic support

### PR DESCRIPTION
**Pull request by HugoStrand**
Dear Igor,

I have added support for the `AllFermionic` class of two-particle Green's function to `pomerol2triqs` and it would be nice to have it in your main repo. Please have a look and let me know what you think.

Cheers, Hugo

### CODE REVIEW

**Comment by krivenko** [comment]
Hi Hugo,

thank you very much for the contribution!
I tried to rederive your relation, and it seems like you don't need that minus sign in front of the r.h.s. of (6).
`\beta\delta\alpha\gamma` is an odd permutation of `\alpha\beta\gamma\delta`, which would give a sign change, but there is another minus in the definition of `G^{(2),Pomerol}`.

**Comment by HugoStrand** [comment]
Dear Igor,

Indeed, I did not see the additional sign in the definition of the two-particle Green's function in Pomerol, where `G2 = -<ccc*c*>`.

Currently I have an inconsistency in my calculations where it seems like my other calculators generates results with "wrong" overall sign. I will have to double check for the correct sign and get back to `pomerol2triqs`.

When I know the outcome I will update this pull request.

Cheers, Hugo

**Comment by krivenko** [comment]
Hey Hugo,

I cherry-picked the `.real()` fix, thank you for it.
What about that minus sign? Our repositories have diverged because of some optimization/parallelization work I've been doing. It would be helpful for both of us to merge this pull request a.s.a.p., before more changes are made.

**Comment by krivenko** [comment]
Dear Hugo,

I am sorry for confusing you! The documentation page of Pomerol gave a wrong definition of `G^2`.
What Pomerol actually computes has no minus sign in front of the correlator!

I updated Pomerol's docs, and fixed pomerol2triqs accordingly.

Best regards,
Igor

**Comment by HugoStrand** [comment]
Dear Igor,

Sorry for the silence, I'm jumping between projects.
Thank you for letting me know about this, it makes my life much less confusing. :)

Cheers, Hugo

**Pull request merged**
