### PR TITLE
Add support for truncateBlocks() (cf. aeantipov/pomerol#16)

### LINKED ISSUE #5: MPI parallelization over two-particle Green's function components?
Dear Igor,

I am not sure whether to post this question at `pomerol2triqs` or `pomerol`. I am calculating two particle Green's functions and it is very slow. I think I am using some mpi parallelism since pomerol says it is distributing work over "processors".

My question is whether I somehow can convince pomerol to compute the different two-particle Green's function elements in parallel? (I have a 4x4x4x4 = 256 elements to calculate in total, so that would be a nice speedup if done in parallel)

Is this possible to do this out of the box with pomerol? If not, what would I have to do to accomplish this?

Cheers, Hugo

### PR DESCRIPTION
**Pull request by krivenko**
Kind of fixes #5.

### CODE REVIEW

**Comment by krivenko** [comment]
@HugoStrand @j-otsuki Could you please have a look before I merge this?

**Comment by j-otsuki** [comment]
Thank you for the support of truncateBlocks, Igor.

I tried to run it, but failed in compilation probably because of incompatibility to TRIQS version. Then, I tried compiling the latest unstable branch of TRIQS, and failed...

I can now only say that the way of calling rho->truncateBlocks looks okay...

**Comment by HugoStrand** [comment]
Dear Junya and Igor,

I have just added a pull request that should make pomerol2triqs work on unstable see #7.

Best, Hugo

**Comment by krivenko** [comment]
> I tried to run it, but failed in compilation probably because of incompatibility to TRIQS version. Then, I tried compiling the latest unstable branch of TRIQS, and failed...

Thanks for taking your time!

Yes, installation of `pomerol2triqs` is a bit of a mess, because it depends on very specific cpp2py and triqs commits. I have just updated `README.md` to make the installation instruction more precise. Unfortunately, C++17 is not an option for me so I cannot go for the current `unstable` branch of triqs.

**Comment by j-otsuki** [comment]
Thank you Hugo and Igor for your comments and PR.

Yes, the development of ``unstable`` branch is too fast for me to follow...

**Pull request merged**
